### ISSUE TITLE
Load Base64 decoded bytes image.

### ISSUE THREAD

**Issue by DipakMahapurkar** [pankaj89/GlideImageView#2]
Hello @pankaj89,
Currently i was loading image url which get from server within image view. Is there any option for load base64 image?. If yes Please add the sample example.

Because in glide library we can do this by using below code:
final byte[] decodedBytes = Base64.decode(pureBase64Encoded, Base64.DEFAULT);
Glide.with(CaptchaFragment.this).load(decodedBytes).crossFade().fitCenter().into(mCatpchaImageView);

How i can achieve above result using this lib.

Thanks !!

**Comment by pankaj89** [comment]
Hello @DipakMahapurkar,

Now you can use version 2.0 which has the methods like load.
