### ISSUE TITLE
Future development 

### ISSUE THREAD

**Issue by Rainer-Lang** [pankaj89/GlideImageView#3]
May I ask what's in your todo list? What features do you plan...? 

I think it's a very interesting and useful lib! Thanks 

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pankaj89** [comment]
Hello @Rainer-Lang thanks for using this library,

I don't have any todo list or future plans, But as any issue faced in my development then i put it here, so our development is modularized and fast.

I want, if you have any idea or some problem you faced in your regular task, then please mention so we can include it in future versions.

Thanks
